

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/graphdb
    username: postgres
    password: 123456
    pool-size: 30
    test-while-idle: true
    test-on-borrow: true
server:
  servlet:
    session:
      cookie:
        same-site: "None"
        secure: true
  port: 3000

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: XMBlMM05rUe4kkwCvVX4i6vPF5rTfnKm
            client-secret: Hd0EmAWj-bNSD2TE2rFZOB8Bjvdz0NkVP21HJE2t_jOjQLzugZBABAvW2g-8jSXG
            scope: openid,profile,email
        provider:
          okta:
            issuer-uri: https://dev-q1p2f8uyj300jl5f.us.auth0.com/
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.hibernate: DEBUG